services:
  torch:
    build: ./docker
    platform: linux/amd64
    volumes:
      - ${MAIN_PATH}:/mlima
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]